name: Windows Checks

on: pull_request

jobs:
  lint:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: pnpm

      - name: Enable Corepack
        run: corepack enable pnpm

      - name: Install and lint
        run: |
          pnpm install --frozen-lockfile
          pnpm test:other
          pnpm lint
          pnpm typecheck
