name: Windows Build

on: pull_request

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: pnpm
      - name: Enable Corepack
        run: corepack enable pnpm
      - name: Install, test, build and package
        run: |
          pnpm install --frozen-lockfile
          pnpm test:app --runInBand
          pnpm build
          pnpm dist:win
